chore: be sure to have keyring installed
zama-ai/concrete-ml pull request #258
Opened 2023-09-20 08:13 UTC by bcm-at-zama

we have seen that, sometimes, keyring was not available, for no obvious reason

closes #https://github.com/zama-ai/concrete-ml-internal/issues/3950

2023-09-20 08:43 UTC, RomanBredehoft requested changes
keyring is a dev dependency in pyproject.toml, could that be the issue (and thus we should put it as a real dependency) ?

2023-09-20 09:09 UTC, bcm-at-zama commented
> keyring is a dev dependency in pyproject.toml, could that be the issue (and thus we should put it as a real dependency) ?

- I would not be against moving it to real dependency
- but, I mean, to `make docker_start` etc, you're already supposed to be a dev, and still, I saw the error
- and remark that we _already_ have some strange keyring install in the makefile

```
setup_env:
	@# The keyring install is to allow pip to fetch credentials for our internal repo if needed
       (...) 
	poetry run python -m pip install keyring
```

So, what should I do? Not sure your solution would make it better, since I am already a dev with a dev setting, and still, I see (sometimes) the problem.

2023-09-20 09:44 UTC, RomanBredehoft commented
I'm not too familiar with this but could it be that we need keyring before installing dependencies or something like this ? 

It just feels weird to blindly add lines like this without knowing the issue !

2023-09-20 09:46 UTC, bcm-at-zama commented
> It just feels weird to "blindly" add lines like this without knowing the issue !

I agree but I have not a 100% reproducible setting for the issue. And here, I thought adding this was better than having the error popping from time to time.

2023-09-20 09:47 UTC, bcm-at-zama commented
@andrei-stoian-zama / @fd0r , what would you do for this issue / PR?

2023-09-20 12:43 UTC, fd0r commented
Well it can't hurt to install it 🤷🏼 

If it's already installed nothing will changed, if it isn't it will fix the issue.

2023-09-20 12:43 UTC, fd0r approved these changes

2023-09-20 15:03 UTC, RomanBredehoft approved these changes
unblocking this PR as I don't have much more to say

2023-09-20 16:01 UTC, bcm-at-zama commented
Let's give the final word to @andrei-stoian-zama

2023-09-21 07:42 UTC, andrei-stoian-zama approved these changes
Ok, looks good to me

2023-09-21 07:43 UTC, andrei-stoian-zama commented
Does it close https://github.com/zama-ai/concrete-ml-internal/issues/3950 ?

2023-09-21 07:52 UTC, merged

2023-09-21 07:53 UTC, bcm-at-zama commented
> Does it close [zama-ai/concrete-ml-internal#3950](https://github.com/zama-ai/concrete-ml-internal/issues/3950) ?

yes. I had written 

closes #https://github.com/zama-ai/concrete-ml-internal/issues/3950

but apparently that's not the right syntax, I have to learn it