chore: updating the CP version
zama-ai/concrete-ml pull request #274
Opened 2023-09-22 09:01 UTC by bcm-at-zama

Testing with the most recent CP
Maybe it will not be merged like that, but at least, should help to check there is no regression.

Also, @andrei-stoian-zama , if we want to check all the fixes are there, we can remove our workarounds in this PR and check. Don't hesitate to push in this branch, or we merge + team pushes in another PR

2023-09-22 09:18 UTC, RomanBredehoft approved these changes, later dismissed

2023-09-22 09:33 UTC, fd0r commented
Will Concrete Python deliver another version until the time we release? If not I would be in favor of not merging this.

2023-09-22 09:45 UTC, bcm-at-zama commented
Anyway: we'll never deliver with nightlies, since they are not publicly available. And yes, we'll have official deliveries. But nightlies are ways for us to check everything is as expected, instead of waiting. So, if I were you, I'd check that the expected fixes are there, in this branch and PR

2023-09-22 11:44 UTC, bcm-at-zama commented
FAILED tests/deployment/test_client_server.py::test_client_server_sklearn[3-KNeighborsClassifier] - RuntimeError: 

KNN failures as well

2023-09-22 11:46 UTC, bcm-at-zama commented
@zama-ai/machine-learning apart the KNN problem, the last nightly CP looks good

2023-09-25 08:33 UTC, fd0r submitted a review, later dismissed

2023-09-25 08:55 UTC, RomanBredehoft commented
conflicting files

2023-09-25 09:16 UTC, bcm-at-zama commented
yes but what do you want to do with this PR, first? are we going to merge it or not? if not, nothing to take care with the licenses. Are you going to test removing the workarounds in this PR, or elsewhere? @RomanBredehoft @andrei-stoian-zama

2023-09-26 09:34 UTC, fd0r submitted a review, later dismissed

2023-09-26 09:46 UTC, RomanBredehoft commented on src/concrete/ml/sklearn/base.py
> -            kwargs["configuration"] = force_mono_parameter_in_configuration(configuration)
I believe you can now remove `force_mono_parameter_in_configuration` from our source code !

2023-09-26 11:16 UTC, andrei-stoian-zama commented
> yes but what do you want to do with this PR, first? are we going to merge it or not? if not, nothing to take care with the licenses. Are you going to test removing the workarounds in this PR, or elsewhere? @RomanBredehoft @andrei-stoian-zama

Yes, I also added the workaround removal , see the Closes section

2023-09-26 12:42 UTC, RomanBredehoft requested changes
this PR should remove `force_mono_parameter_in_configuration` from common/utils.py as it's not used anymore

2023-09-26 14:14 UTC, kcelia commented on src/concrete/ml/sklearn/base.py
> -            configuration = force_mono_parameter_in_configuration(args[1])
You need to delete the import of `from ..common.utils import force_mono_parameter_in_configuration` from base.py
And from src/concrete/ml/common/utils.py as well: 
````
from concrete.fhe import ParameterSelectionStrategy
from concrete.fhe.compilation.configuration import Configuration
```
+
```
def force_mono_parameter_in_configuration(configuration: Optional[Configuration], **kwargs) ....
````

2023-09-27 12:46 UTC, RomanBredehoft commented
also I think you need to rebase @andrei-stoian-zama , you got a flaky that is currently skipped on main

2023-09-27 12:51 UTC, RomanBredehoft requested changes
@andrei-stoian-zama maybe you missed my last request for changes : 
> this PR should remove force_mono_parameter_in_configuration from common/utils.py as it's not used anymore

2023-09-27 15:34 UTC, fd0r submitted a review, later dismissed

2023-09-28 07:53 UTC, kcelia approved these changes

2023-09-28 07:56 UTC, fd0r approved these changes

2023-09-28 08:07 UTC, RomanBredehoft approved these changes

2023-09-28 08:08 UTC, merged