minor doc fixes for release
zama-ai/concrete-ml pull request #294
Opened 2023-09-26 12:59 UTC by andrei-stoian-zama

Closes https://github.com/zama-ai/concrete-ml-internal/issues/3974
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3972
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4020
Closes https://github.com/zama-ai/concrete-ml-internal/issues/3973

2023-09-26 15:40 UTC, RomanBredehoft commented on docs/built-in-models/linear.md
> +cml_model = LogisticRegression(model, X_train, n_bits=8)
it's `LogisticRegression.from_sklearn_model` !

2023-09-26 15:41 UTC, RomanBredehoft commented on docs/built-in-models/linear.md
> +```
also maybe I would add the compile + predict steps to better show that this does not replace other steps (like the compile one) , as you wish

2023-09-26 15:41 UTC, RomanBredehoft requested changes
thanks a lot for this ! I have a few comments

2023-09-27 14:08 UTC, kcelia commented on README.md
> +- [FHE neural network splitting for client/server deployment](use_case_examples/cifar/cifar_brevitas_with_model_splitting): explains how to split a computationally-intensive neural network model in t
explain (like you did above) or explains ?

2023-09-27 14:22 UTC, kcelia commented on docs/developer-guide/api/README.md
> -- [`utils.set_multi_parameter_in_configuration`](./concrete.ml.common.utils.md#function-set_multi_parameter_in_configuration): Build a Configuration instance with multi-parameter strategy, unless one
have you meant to delete mono ?  [`utils.force_mono_parameter_in_configuration`](./concrete.ml.common.utils.md#function-force_mono_parameter_in_configuration): Force configuration to mono-parameter strategy.

2023-09-27 14:25 UTC, kcelia commented on docs/developer-guide/api/concrete.ml.deployment.fhe_client_server.md
> +- <b>`zip_path`</b> (Path):  The path to the client or server zip file that contains the version.json  file to check.
extra space in `(Path):  The `

2023-09-27 14:26 UTC, kcelia commented on docs/developer-guide/api/concrete.ml.deployment.fhe_client_server.md
> +- <b>`ValueError`</b>:  If at least one version mismatch is found.
extra space in `</b>:  If `

2023-09-27 14:52 UTC, fd0r approved these changes
Good with me, but @RomanBredehoft 's comment wasn't addressed

2023-09-27 15:07 UTC, RomanBredehoft approved these changes

2023-09-27 15:07 UTC, merged