chore: update privacy tree paper experiment
zama-ai/concrete-ml pull request #371
Opened 2023-10-17 11:33 UTC by jfrery

closes https://github.com/zama-ai/concrete-ml-internal/issues/4089

2023-10-17 16:39 UTC, RomanBredehoft approved these changes
thanks !

2023-10-17 16:41 UTC, RomanBredehoft requested changes
actually, would it be possible to better format the printed tables ? I guess there are meant to be put in a latex format, but it's not very readable here

2023-10-17 17:41 UTC, jfrery commented
> actually, would it be possible to better format the printed tables ? I guess there are meant to be put in a latex format, but it's not very readable here

The main point is to copy paste directly to latex. But maybe we can instead print the dataframe yes

2023-10-17 19:29 UTC, fd0r submitted a review, later dismissed

2023-10-18 08:32 UTC, RomanBredehoft commented
> The main point is to copy paste directly to latex. But maybe we can instead print the dataframe yes

I don't really agree, imo the main point of putting this notebook in our directory is to give our users the possibility to be able to see where these timings and plots come from. So it should be kept easily readable like the previous one ! We can keep the latex format  in some internal repo if we want

2023-10-18 09:52 UTC, kcelia commented on docs/advanced_examples/ExperimentPrivacyTreePaper.ipynb
> +      "RandomForestClassifier on spambase (#features: 57) -> Acc: 0.9089, Acc (fp32): 0.9184, FHE inference time: 6.88s\n",
I agree, this print is not visually appealing.

I can suggest to reformat the print, like:


```
        shift = 52 - len(f"{cls.__name__} on {key_dataset}")

        print(
            f"{cls.__name__} on {key_dataset} {'->':>{shift}} Acc: {np.mean(scores['accuracy']):.4f}, "
            f"Acc (fp32): {np.mean(scores_fp32['accuracy']):.4f}, "
            f"FHE inference time: {scores['inference_time']:.2f}s"
        )

```
![image](https://github.com/zama-ai/concrete-ml/assets/14870263/95f8c164-777d-4e52-8274-0f8da6607831)

2023-10-20 11:57 UTC, andrei-stoian-zama commented
I think it's not that important that the formatting is nice, it's important that we show our results are reproducible. So @jfrery merge this in the form that you want.

2023-10-23 07:00 UTC, kcelia approved these changes

2023-10-23 08:49 UTC, RomanBredehoft approved these changes

2023-10-23 09:45 UTC, merged