fix: make skorch import fail without error
zama-ai/concrete-ml pull request #511
Opened 2024-02-14 10:52 UTC by fd0r

Skorch is not available in the step of the release that launches the import of skorch.
This makes the import fail without error.

2024-02-14 10:54 UTC, RomanBredehoft commented on Makefile
> +  poetry run python -c "import skorch" || true # Details above
not well indented

2024-02-14 10:56 UTC, RomanBredehoft requested changes
the new line is not well indented 

also, although this would probably fix the issue, I believe the initial error is different (problem with poetry + the clone install script), so this should be temporary (not worth a fixme I'll try to fix it today)

2024-02-14 12:17 UTC, RomanBredehoft approved these changes

2024-02-14 15:53 UTC, RomanBredehoft approved these changes

2024-02-15 10:04 UTC, kcelia approved these changes

2024-02-15 10:12 UTC, merged