fix: update qgpt2_class.py to fix typo
zama-ai/concrete-ml pull request #651
Opened 2024-04-25 08:14 UTC by fd0r

This commit fixes a bug in use_cases_examples/llm/qgpt2_class.py demo where `simulate` was not called properly.

It raised `TypeError: unsupported operand type(s) for /: 'method' and 'int'` because `<bound method Circuit.simulate>` was not called.

2024-04-25 08:32 UTC, RomanBredehoft approved these changes

2024-04-25 08:34 UTC, RomanBredehoft requested changes
we can merge it but CLA is not happy, so let's make sure everything is right

2024-04-25 12:12 UTC, RomanBredehoft approved these changes

2024-04-25 12:19 UTC, fd0r commented
Only waiting for @HugoLB0 to sign the CLA.

2024-04-29 07:27 UTC, aquint-zama commented
@cla-bot check

2024-04-29 07:30 UTC, merged