Explain torch compile error messages, improve PTQ vs QAT doc
zama-ai/concrete-ml pull request #730
Opened 2024-06-13 13:41 UTC by andrei-stoian-zama

Closes https://github.com/zama-ai/concrete-ml-internal/issues/4414
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4387
Closes https://github.com/zama-ai/concrete-ml-internal/issues/4487

2024-06-13 14:15 UTC, RomanBredehoft requested changes
thanks ! But I don't think it closes https://github.com/zama-ai/concrete-ml-internal/issues/4414 as this issue is more about the error message itself, not the doc

2024-06-13 14:19 UTC, RomanBredehoft commented
also might be worth to consider https://github.com/zama-ai/concrete-ml-internal/issues/4498 in this PR as well, if possible 🙏

2024-06-13 14:40 UTC, yuxizama reviewed
I suggest the following format for users to easily find solutions when they encounter some errors. Wdyt?

### Common Compilation erros 

#### Bit width limits
**Error message**: `This is the error message`
**Cause:** This error can occur when rounding_threshold_bits is not used and accumulated intermediate values in the computation exceed 16-bits. TLU input maximum bit-width is exceeded
**Possible solutions**: 
- Reduce quantization n_bits. However, this may reduce accuracy. When quantization n_bits must be below 6, it is best to use [Quantization Aware Training](https://github.com/zama-ai/concrete-ml/blob/docs/discuss_error_messages/docs/deep-learning/fhe_friendly_models.md).
- Use rounding_threshold_bits. This feature is described [here](https://github.com/zama-ai/concrete-ml/blob/docs/discuss_error_messages/docs/explanations/advanced_features.md#rounded-activations-and-quantizers). It is recommended to use the [fhe.Exactness.APPROXIMATE](https://github.com/zama-ai/concrete-ml/blob/docs/discuss_error_messages/docs/references/api/concrete.ml.torch.compile.md#function-compile_torch_model) setting, and set the rounding bits to 1 or 2 bits higher than the quantization n_bits
- Use [pruning](https://github.com/zama-ai/concrete-ml/blob/docs/discuss_error_messages/docs/explanations/pruning.md)

#### Crypto-parameters
**Error message:** `This is the error message`
**Cause:** This is the cause
**Possible sulutions:**
- Solution 1 
- Solution 2


#### Quantization
**Error message:** `This is the error message`
**Cause:** This is the cause
**Possible sulutions:**
- Solution 1 
- Solution 2

2024-06-17 09:00 UTC, RomanBredehoft submitted a review, later dismissed

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +One can perform the inference on clear data in order to evaluate the impact of quantization and of FHE computation on the accuracy of their model. See [this section](../deep-learning/fhe_assistant.md
```suggestion
You can perform the inference on clear data in order to evaluate the impact of quantization and of FHE computation on the accuracy of their model. See [this section](../deep-learning/fhe_assistant.md#simulation) for more details. Two approaches exist:
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/fhe_assistant.md
> +The most common compilation errors stem from the following causes:
```suggestion

```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/fhe_assistant.md
> +**Cause**: This error can occur when `rounding_threshold_bits` is not used and accumulated intermediate values in the computation exceed 16-bits. The most common approaches to fix this issue are:
```suggestion
**Cause**: This error can occur when `rounding_threshold_bits` is not used and accumulated intermediate values in the computation exceed 16 bits. 
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/fhe_assistant.md
> +**Error message**: `RuntimeError: NoParametersFound` is raised by the compiler
```suggestion
**Error message**: `RuntimeError: NoParametersFound`
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/fhe_assistant.md
> +**Cause**: This error is a due to missing quantization operators in the model that is imported as a quantized aware training model. See [this guide](../deep-learning/fhe_friendly_models.md) on how to
```suggestion
**Cause**: This error occurs when the model imported as a quantized-aware training model lacks quantization operators. See [this guide](../deep-learning/fhe_friendly_models.md) on how to use Brevitas layers. This error message indicates that some layers do not take inputs quantized through `QuantIdentity` layers.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/fhe_assistant.md
> +Compilation errors due to FHE incompatible models, such as maximum bit-width exceeded or `NoParametersFound` can be debugged by examining the bit-widths associated with various intermediate values of
```suggestion
For compilation errors due to FHE-incompatible models, such as maximum bit-width exceeded or `NoParametersFound`, you can debug them by examining the bit-widths associated with various intermediate values of the FHE computation.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/fhe_assistant.md
> +On the other hand, `NoParametersFound` is encountered when using `rounding_threshold_bits`. When using this setting, the 16-bit accumulator limit is relaxed. However, reducing bit-width, or reducing
```suggestion
On the other hand, `NoParametersFound` occurs when using `rounding_threshold_bits`. With this setting, the 16-bit accumulator limit is relaxed. However, the following solution could help: 
- Reduce bit width
- Reduce the `rounding_threshold_bits`
- Use the [`fhe.Exactness.APPROXIMATE`](../references/api/concrete.ml.torch.compile.md#function-compile_torch_model) rounding method.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +- [Quantization Aware Training (QAT)](../explanations/quantization.md) requires using custom layers, but can quantize weights and activations to low bit-widths. Concrete ML works with [Brevitas](../e
```suggestion
- [**Quantization Aware Training (QAT)**](../explanations/quantization.md) : QAT requires using custom layers, but can quantize weights and activations to low bit widths. Concrete ML works with [Brevitas](../explanations/inner-workings/external_libraries.md#brevitas), a library providing QAT support for PyTorch. To use this mode, compile models using `compile_brevitas_qat_model`
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +- Post-training Quantization: in this mode a vanilla PyTorch model can be compiled. However, when quantizing weights & activations to fewer than 7 bits the accuracy can decrease strongly. On the othe
```suggestion
- **Post-training Quantization**: This mode allows a vanilla PyTorch model to be compiled. However, when quantizing weights & activations to fewer than 7 bits, the accuracy can decrease strongly. On the other hand, depending on the model size, quantizing with 6-8 bits can be incompatible with FHE constraints. To use this mode, compile models with `compile_torch_model`.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +Both approaches should be used with the `rounding_threshold_bits` parameter set accordingly. The best values for this parameter need to be determined through experimentation. A good initial value to
```suggestion
Both approaches require the `rounding_threshold_bits` parameter to be set accordingly. The best values for this parameter need to be determined through experimentation. A good initial value to try is `6`. See [here](../explanations/advanced_features.md#rounded-activations-and-quantizers) for more details.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +With QAT, the PyTorch/Brevitas models, created following the example above, require the user to configure quantization parameters such as `bit_width` (activation bit-width) and `weight_bit_width`. Wh
```suggestion
With QAT (the PyTorch/Brevitas models created following the example above), you need to configure quantization parameters such as `bit_width` (activation bit-width) and `weight_bit_width`. When using this mode, set `n_bits=None` in the `compile_brevitas_qat_model`.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +With PTQ, the user needs to set the `n_bits` value in the `compile_torch_model` function. A trade-off between accuracy and FHE compatibility and latency must be determined manually.
```suggestion
With PTQ, you need to set the `n_bits` value in the `compile_torch_model` function and must manually determine the trade-off between accuracy, FHE compatibility, and latency.
```

2024-06-17 09:54 UTC, yuxizama commented on docs/deep-learning/torch_support.md
> +The quantization parameters, along with the number of neurons on each layer, will determine the accumulator bit-width of the network. Larger accumulator bit-widths result in higher accuracy but slowe
```suggestion
The quantization parameters, along with the number of neurons on each layer, will determine the accumulator bit width of the network. Larger accumulator bit widths result in higher accuracy but slower FHE inference time.
```

2024-06-17 12:09 UTC, RomanBredehoft submitted a review, later dismissed

2024-06-17 13:06 UTC, RomanBredehoft approved these changes, later dismissed

2024-06-17 14:08 UTC, RomanBredehoft approved these changes

2024-06-17 15:18 UTC, merged