chore: minor clarifications in the WP notebook
zama-ai/concrete-ml pull request #779
Opened 2024-07-04 13:58 UTC by bcm-at-zama

Small clarifications in the WP notebook

2024-07-08 10:09 UTC, RomanBredehoft commented on use_case_examples/white_paper_experiment/WhitePaperExperiments.ipynb
> +    "Here is a recap of the results obtained by running this notebook on a `m6i` instance, compared to the results in the whitepaper [1]."
I would specify `m6i.metal` here as there are several m6i possible instances

2024-07-08 10:10 UTC, RomanBredehoft commented on use_case_examples/white_paper_experiment/WhitePaperExperiments.ipynb
> +    "A pre-computed comparison to a `hpc7a` instance with 192 vCPU is also shown when running this notebook on a large server machine."
same, I would specify `hpc7a.96xlarge` here

2024-07-08 10:10 UTC, RomanBredehoft requested changes
I would be more precise on the machines we are using !

2024-07-09 09:02 UTC, bcm-at-zama commented on use_case_examples/white_paper_experiment/WhitePaperExperiments.ipynb
> +    "Here is a recap of the results obtained by running this notebook on a `m6i` instance, compared to the results in the whitepaper [1]."
done

2024-07-09 09:04 UTC, bcm-at-zama commented on use_case_examples/white_paper_experiment/WhitePaperExperiments.ipynb
> +    "A pre-computed comparison to a `hpc7a` instance with 192 vCPU is also shown when running this notebook on a large server machine."
done

2024-07-09 09:05 UTC, bcm-at-zama commented
Done @RomanBredehoft

2024-07-09 09:25 UTC, RomanBredehoft approved these changes
thanks !

2024-07-16 12:57 UTC, fd0r approved these changes

2024-07-23 13:59 UTC, bcm-at-zama commented
Can we merge that please @andrei-stoian-zama

2024-07-23 14:03 UTC, merged