We might support 3 12 python [WIP]
zama-ai/concrete-ml pull request #847
Opened 2024-08-27 14:28 UTC by bcm-at-zama

I've not done the job completely, but it appears we can find a toml which locks well. Do you want me to try to continue and have a support for 3.12, @andrei-stoian-zama ? If yes: I'll just wait #701 is merge and then do.

2024-08-28 09:29 UTC, bcm-at-zama commented
CP 3.11 installation was fixed: it was a bad command line.

2024-08-28 15:10 UTC, bcm-at-zama commented
Looks good to me, but I haven't ran it on 3.12.

2024-08-28 15:16 UTC, bcm-at-zama commented
Added a reversible commit to try 3.12 on the PR

2024-08-28 15:34 UTC, bcm-at-zama commented
We have an issue in `make sync_env`:

```
 • Installing websocket-client (1.8.0)

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.
  
  Cannot import 'setuptools.build_meta'

  at /opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.23.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "numpy (==1.23.5)"'.

make: *** [Makefile:32: setup_env] Error 1
```

2024-08-28 15:36 UTC, bcm-at-zama commented
Trying on my machine

2024-08-28 15:51 UTC, bcm-at-zama commented
Trying to see if I can change a bit the toml and make sync_env with 3.12

2024-08-29 16:51 UTC, bcm-at-zama commented
@andrei-stoian-zama : do I let you finish this PR?

2024-10-29 15:01 UTC, andrei-stoian-zama commented on pyproject.toml
> +url = "https://pypi.zama.ai/gpu"
don't forget to switch back

2024-10-29 15:02 UTC, andrei-stoian-zama commented on pyproject.toml
> +protobuf = "3.20.3"
I'm not sure why we need these specific versions now.. didn't we need them already when supporting python3.11 ?

2024-10-29 15:03 UTC, andrei-stoian-zama commented on script/make_utils/setup_os_deps.sh
> +        wget pipx adduser && \
with ubuntu>23 we install poetry using `pipx`

2024-10-29 15:04 UTC, andrei-stoian-zama commented on docker/Dockerfile.dev
> +RUN (pipx install poetry && pipx ensurepath) || \
if installation fails with `pipx` (ubuntu <=22), install in the original manner and add the user's local `site-packages` to the path

2024-10-29 15:04 UTC, andrei-stoian-zama commented on docker/Dockerfile.dev
> +FROM ubuntu:${UBUNTU_BASE}
can now be parametrized by the caller

2024-10-29 15:04 UTC, andrei-stoian-zama commented on Makefile
> +$(warning now we reached ifeq DEV_DOCKER_PYTHON=$(DEV_DOCKER_PYTHON))
remove this warning

2024-10-29 15:05 UTC, andrei-stoian-zama commented on Makefile
> +	BUILD_ARGS+="--build-arg OS_DEPS_ARG=linux-install-python "; \
remove this `OS_DEPS_ARG`

2024-10-30 11:57 UTC, andrei-stoian-zama commented on .github/workflows/continuous-integration.yaml
> +        default: "3.12"
revert to 3.8 here

2024-10-31 15:20 UTC, andrei-stoian-zama commented on script/make_utils/setup_os_deps.sh
> -        python3 -m pip install --no-cache-dir --ignore-installed poetry==1.7.1 && \
we need to readd this for the CI to work

2024-11-20 19:09 UTC, jfrery requested changes
This is a 1h45 minutes test... So 30 min + increase. Why is that?

2024-11-20 19:21 UTC, jfrery commented
I launched a 3.12 CML test https://github.com/zama-ai/concrete-ml/actions/runs/11940082085/job/33282105181

2024-11-26 14:00 UTC, jfrery requested changes
We still need the CML 3.12 test to pass -> https://github.com/zama-ai/concrete-ml/actions/runs/12032176976

2024-11-27 11:47 UTC, kcelia commented on docs/advanced_examples/GLMComparison.ipynb
> +   "execution_count": null,
Some notebooks haven't run normally, it's worth refreshing them with the CI action

2024-12-04 10:20 UTC, jfrery approved these changes
thanks for the test speed up!

2024-12-04 10:21 UTC, merged