chore: add readme in root folder of deployment use case + fix cifar
zama-ai/concrete-ml pull request #876
Opened 2024-09-19 12:55 UTC by jfrery

closes https://github.com/zama-ai/concrete-ml-internal/issues/4600

ref #873 
cc @bcm-at-zama

2024-09-24 21:04 UTC, andrei-stoian-zama approved these changes

2024-09-25 09:29 UTC, andrei-stoian-zama requested changes
Wait.. why are we duplicating the cifar use case here in deployment ?

2024-09-25 10:03 UTC, jfrery commented
> Wait.. why are we duplicating the cifar use case here in deployment ?

We are duplicating the model. There was [a change](https://github.com/zama-ai/concrete-ml/pull/538/files#diff-0ce00a4975eb5fe4698e298d62c3c25aab55e01de9e16e91c4b384e2c1baa848L10-R10) to use the cifar10 training model but it was not imported.

2024-10-28 15:35 UTC, andrei-stoian-zama approved these changes

2024-10-28 15:39 UTC, merged