feat: add logs + evaluation llama lora
zama-ai/concrete-ml pull request #962
Opened 2024-12-17 10:22 UTC by jfrery

2025-02-10 14:58 UTC, andrei-stoian-zama requested changes
Do you need to upload the math problem notebook ? 

Could you re-run the LLAMA and GPT2 notebooks to make sure they work well. Maybe we should switch them to dyanmic quant as well ?

2025-02-10 14:58 UTC, andrei-stoian-zama commented on src/concrete/ml/torch/hybrid_model.py
> +        if next(self.private_module.parameters()).device != x.device:
can't there be multiple `parameters` in the `private_module`, why not iterate ?

2025-02-10 14:58 UTC, andrei-stoian-zama commented on src/concrete/ml/torch/hybrid_model.py
> +                    # const_inp.values = const_inp.qvalues.astype(numpy.float32)
should't we allow this optimization if the quantization is static ?

2025-02-10 14:58 UTC, andrei-stoian-zama commented on src/concrete/ml/torch/lora.py
> -    def toggle_calibrate(self, enable: bool = True):
isn't this method used in the Gpt2 notebook?

2025-02-10 14:58 UTC, andrei-stoian-zama commented on use_case_examples/lora_finetuning/README.md
> +### Evaluation Script
you mention the math problem training, but where is the notebook for it?

2025-02-10 14:58 UTC, andrei-stoian-zama commented on use_case_examples/lora_finetuning/README.md
> +- **ST-ST**: Static per-Tensor quantization with fixed ranges
do we need to showcase static quantization ? we know it doesn't work well.

2025-02-17 12:10 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> +        """
Is there a reason why `import concrete_ml_extensions as fhext` is not at the beginning of the script?

2025-02-17 12:13 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
>              self.glwe_crypto_params
mmm 
i thought that `self.fhext.create_private_key(` generates:
1-  the private key
Then to get the compressed key, we use: `fhext.deserialize_compression_key(server_key.serialize())`

2025-02-17 12:38 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> +        weight_zp = torch.round((q_min - w_min_vals) / weight_scale).to(torch.float32)
In affine quantization, the zero point is an int, so maybe we should cast it to torch.int32

2025-02-17 15:31 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> -        # Need to slice the last GLWE (this will be improved in later cml-extensions)
why did you remove this comment ?
it's not the case anymore?

2025-02-17 15:31 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> -        # The GLWE backend needs uint64 encoding for both neg/pos values
same comment

2025-02-18 08:31 UTC, jfrery commented on src/concrete/ml/torch/hybrid_model.py
> +        if next(self.private_module.parameters()).device != x.device:
Yes better check if any of the param is not on the same device.

2025-02-18 08:32 UTC, jfrery commented on src/concrete/ml/torch/hybrid_model.py
> +                    # const_inp.values = const_inp.qvalues.astype(numpy.float32)
Ok I add it back for static quantization. Not sure the gain though.

2025-02-18 08:34 UTC, jfrery commented on src/concrete/ml/torch/lora.py
> -    def toggle_calibrate(self, enable: bool = True):
Good catch. I will update GPT2 notebook. We should rerun the two notebook anyway.

2025-02-18 08:35 UTC, jfrery commented on use_case_examples/lora_finetuning/README.md
> +### Evaluation Script
There is no notebook. The line after mentions the `eval.py` script

2025-02-18 08:38 UTC, jfrery commented on use_case_examples/lora_finetuning/README.md
> +- **DTen-ST**: Dynamic/Static hybrid quantization
I think the information should remain somewhere. Should I create another .md where I store this?

2025-02-18 08:58 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> +        """
Yes, the library might not be installed / be available. Since this file is imported in the hybrid model, we don't want to import it by default.

2025-02-18 09:10 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> +        weight_q, weight_scale, weight_zp, sum_w = self._per_channel_weight_quantization(
yes you are right. We do input dynamic quantization. Static per channel weight quantization.

These weight shouldn't be re-computed everytime. Ideally I should store them back in the quantized module. I will add a FIXME

2025-02-18 09:14 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
>              self.glwe_crypto_params
```
#[pyfunction]
fn cpu_create_private_key(
    crypto_params: &MatmulCryptoParameters,
) -> PyResult<(PrivateKey, CpuCompressionKey)> {
    let (glwe_secret_key, post_compression_glwe_secret_key, compression_key) =
        create_private_key_internal(crypto_params);

    return Ok((
        PrivateKey {
            inner: glwe_secret_key,
            post_compression_secret_key: post_compression_glwe_secret_key,
        },
        CpuCompressionKey {
            inner: compression_key,
            buffers: compression::CpuCompressionBuffers::<Scalar> { _tmp: PhantomData },
        },
    ));
}
```

create_private_key returns the compressed key as well

2025-02-18 09:15 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> -        # Need to slice the last GLWE (this will be improved in later cml-extensions)
good catch. It's still the case.

2025-02-18 09:16 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> -        # The GLWE backend needs uint64 encoding for both neg/pos values
yep... adding it back.

2025-02-18 11:01 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
>              self.glwe_crypto_params
thanks

2025-02-18 12:27 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> +        weight_zp = torch.round((q_min - w_min_vals) / weight_scale).to(torch.float32)
@andrei-stoian-zama figured this out. And doing a quick experiment with torch / numpy float32 vs int32 matmul confirms it.

I think both int32 matmul bypass BLAS optimization...

2025-02-18 13:13 UTC, kcelia commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> -        # Add a B=1 dimension if needed
What about those comments ?

2025-02-19 10:05 UTC, andrei-stoian-zama requested changes
1. there's a bug in the GPT2 notebook when LORA layers are activated.
```
# Inference using the fine-tuned model with LoRA weights
# Seed for reproducibility
torch.manual_seed(SEED)

fine_tuned_model.enable_adapter_layers()
prompt = "who invented FHE?"
generate_and_print(prompt, fine_tuned_model, tokenizer, SEED)
     
who invented FHE? , the,, a, in, at, and,
```

2. I think `use_dynamic_quantization` should be enabled by default, and it should be auto-disable if the model is not fully linear. 


3. In a second PR can we move the `eval.py` code to a notebook ?

2025-02-20 10:16 UTC, jfrery commented on src/concrete/ml/quantization/linear_op_glwe_backend.py
> -        # Add a B=1 dimension if needed
I added them back

2025-02-20 10:19 UTC, jfrery commented
> 1. there's a bug in the GPT2 notebook when LORA layers are activated.
> 
> ```
> # Inference using the fine-tuned model with LoRA weights
> # Seed for reproducibility
> torch.manual_seed(SEED)
> 
> fine_tuned_model.enable_adapter_layers()
> prompt = "who invented FHE?"
> generate_and_print(prompt, fine_tuned_model, tokenizer, SEED)
>      
> who invented FHE? , the,, a, in, at, and,
> ```

No this is because we executed GLWE with 16 bits which has overflows. I updated the notebook with 8 bits + dynamic quant. It's much better.

>  2. I think `use_dynamic_quantization` should be enabled by default, and it should be auto-disable if the model is not fully linear.

GPT2 uses the hybrid model to train and not lora so it can't be default. Otherwise it's default for lora training yes. Dynamic quantization is only possible for GLWE currently which itself only work with linear layers. 

> 3. In a second PR can we move the `eval.py` code to a notebook ?

Yes we can.

2025-02-20 13:59 UTC, andrei-stoian-zama approved these changes
Looks good!

2025-02-20 17:34 UTC, merged